### ISSUE TITLE
Instant Preview does not work on Mac (Unity Editor crash)

### ISSUE THREAD

**Issue by jtfrom9** [google-ar/arcore-unity-sdk#710]
### SPECIFIC ISSUE ENCOUNTERED
Unity Editor crash when just start Instant Preview with latest Unity and 1.16.0.

### VERSIONS USED
- Unity: 2019.3.10f1
- ARCore SDK for Unity: 1.16
- Device manufacturer, model, and O/S: MacOS 10.14.6
- ARCore: 1.16.200302046
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: samsung/dreamqltezh/dreamqltechn:8.0.0/R16NW/G9500ZHU3CRG5:user/release-keys

### STEPS TO REPRODUCE THE ISSUE

1. Create New Project
2. Setup ARCore SDK according to [here](https://developers.google.com/ar/develop/unity/quickstart-android)
3. Open HelloAR Scene
4. Play

### WORKAROUNDS (IF ANY)
No problem with 2019.3.0f6.
After 2019.3.1 seems to have problems

### ADDITIONAL COMMENTS
attached detailed crash log

[crash.log](https://github.com/google-ar/arcore-unity-sdk/files/4491865/crash.log)
[Editor.log](https://github.com/google-ar/arcore-unity-sdk/files/4491867/Editor.log)

**Comment by Animator69** [comment]
Even I am facing the same issue, with SDK v1.18

**Comment by jtfrom9** [comment]
according to https://github.com/googlesamples/arcore-depth-lab
**Instant Preview is not enabled for Depth API yet.** 
so 1.18 has another problems

**Comment by Gjohnson6** [comment]
This issue should be fixed in 1.19. Feel free to reopen this issue if you have any more problems.

**Comment by jtfrom9** [comment]
@Gjohnson6 
Do you mean the only thing that will be fixed in 1.19 is the point mentioned in https://github.com/googlesamples/arcore-depth-lab that instant preview is not enabled for the Depth API yet ?
I'm hoping that the issue I first pointed out in 1.16 (same issue in 1.17) will be fixed.
Instant Preview doesn't work at all on macs (except for 2019.3.0f6 and earlier).

**Comment by Gjohnson6** [comment]
The editor crashing when running Instant Preview on Mac is what will be fixed with 1.19, sorry for not being specific. The Depth API will still not be enabled when using Instant Preview.

**Comment by jtfrom9** [comment]
@Gjohnson6 not fixed yet with 1.19. please reopen this issue. 
Error message is completely same with my first report. 
Please try to repro according to my step.

**Comment by jtfrom9** [comment]
<img width="849" alt="Screen Shot 2020-09-01 at 11 59 46" src="https://user-images.githubusercontent.com/1320102/91790410-b618c380-ec4b-11ea-99de-4dd9f22a2f6d.png">
When I saw this, editor did not cash (but black screen).
Has the use of instant preview changed? I don't think the Switch Platform was needed before. 
If so, I hope this page is updated
https://developers.google.com/ar/develop/unity/instant-preview

**Comment by jtfrom9** [comment]
![Screen Shot 2020-09-01 at 12 15 33](https://user-images.githubusercontent.com/1320102/91791047-1b20e900-ec4d-11ea-9050-247833cb6c3b.png)
And crash case (Switch Platform to Android), I saw this for a second, then CRASH

**Comment by Gjohnson6** [comment]
The Instant Preview documentation does mention setting the build target to Android in the troubleshooting section, although it might be good if we moved it to the Using Instant Preview section: "In Unity's Build Settings, your build platform is set to Android and you have player settings enabled for ARCore. If not, see the Unity quickstart guide for configuration details." 

As for the crash, I will have to look into this and see if I can reproduce it.

**Comment by Gjohnson6** [comment]
Hey, sorry for the long delay, I haven't been able to reproduce this issue with ARCore 1.19. Can you go to the Help menu in the Unity Editor and generate a bug report using the Capture ARCore Bug Report button and attach the file here? Thanks.

**Comment by jtfrom9** [comment]
Let me make sure your environment. What version your mac is ?

**Comment by jtfrom9** [comment]
And please provide whole project that works correctly if possible

**Comment by Gjohnson6** [comment]
I'm running macOS 10.15.6 and I'm using the sample scenes in the 1.19 SDK likeHelloAR to test.

**Comment by jtfrom9** [comment]
[arcore_unity_editor_bug_report_20200930_050350.txt](https://github.com/google-ar/arcore-unity-sdk/files/5303924/arcore_unity_editor_bug_report_20200930_050350.txt)

@Gjohnson6 Sorry I'm late, attached.

**Comment by jtfrom9** [comment]
[arcore_unity_editor_bug_report_20200930_050911.txt](https://github.com/google-ar/arcore-unity-sdk/files/5303957/arcore_unity_editor_bug_report_20200930_050911.txt)
@Gjohnson6  Sorry for late, attached.
